language: python
matrix:
  include:
    - python: "2.7"
      env: 
        - appid=pgk9e8orv8l9coak1rjht1avt2f4o9kptb0au0by5vbk9upb 
        - appkey=AJpoJrqy1aliyXvcs0SwWrsy
        - masterKey=Uk6DT2Mc2kCACvLyi3PU60p3
        - use_region=US
    - python: "2.6"
      env: 
        - appid=8FfQwpvihLHK4htqmtEvkNrv
        - appkey=eE9tNOcCiWoMHM1phxY41rAz
        - masterKey=75zAjEJSj7lifKQqKSTryae9
        - use_region=US

sudo: false

# command to install dependencies
install:
  - "pip install -e .[test]"

# command to run tests
script: nosetests --nologcapture 
